LineLength:
  Enabled: false

Lambda:
  Enabled: false

MethodLength:
  Max: 35

ClassLength:
  Max: 125

CyclomaticComplexity:
  Max: 10

PerceivedComplexity:
  Max: 10

HandleExceptions:
  Enabled: false

HashSyntax:
  Enabled: false

AbcSize:
  Enabled: false

GuardClause:
  MinBodyLength: 5

NumericLiterals:
  Enabled: false
